// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR8kYXMlMhzgOP0kvyGuajZ8S5GC9zm3I',
    appId: '1:397286143608:web:dcc640b1b9dd1c12bb1f8d',
    messagingSenderId: '397286143608',
    projectId: 'rapture-ready-app',
    authDomain: 'rapture-ready-app.firebaseapp.com',
    storageBucket: 'rapture-ready-app.firebasestorage.app',
    measurementId: 'G-7RPH8DDMV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtQxivpL8_KRXusinb72rLxN1nTeueZKk',
    appId: '1:397286143608:android:52ca53fda1cb05f4bb1f8d',
    messagingSenderId: '397286143608',
    projectId: 'rapture-ready-app',
    storageBucket: 'rapture-ready-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApd_PZlTx5Vmw1fwTmL-F4uSshuXjdJlg',
    appId: '1:397286143608:ios:58c62e2c0c7da9e4bb1f8d',
    messagingSenderId: '397286143608',
    projectId: 'rapture-ready-app',
    storageBucket: 'rapture-ready-app.firebasestorage.app',
    iosBundleId: 'com.jeremyfarris.raptureready',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApd_PZlTx5Vmw1fwTmL-F4uSshuXjdJlg',
    appId: '1:397286143608:ios:e5c7f488c5d8550fbb1f8d',
    messagingSenderId: '397286143608',
    projectId: 'rapture-ready-app',
    storageBucket: 'rapture-ready-app.firebasestorage.app',
    iosBundleId: 'com.wVertiZontalMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR8kYXMlMhzgOP0kvyGuajZ8S5GC9zm3I',
    appId: '1:397286143608:web:0d118dc76975ae70bb1f8d',
    messagingSenderId: '397286143608',
    projectId: 'rapture-ready-app',
    authDomain: 'rapture-ready-app.firebaseapp.com',
    storageBucket: 'rapture-ready-app.firebasestorage.app',
    measurementId: 'G-FX4Q3Q6WCZ',
  );

}